version: '2'
services:
  php_prova:
    container_name: php_prova
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .\src/:/var/www/html
    restart: always
    ports:
      - 8080:80
    links:
      - db
    entrypoint: bash -c "service apache2 restart && tail -f /dev/null"
    networks:
      - mysql-compose-network
  db:
    container_name: mysql
    image: mysql:5.7
    ports: 
      - 3310:3306
    volumes:
      - .\db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123123
      - MYSQL_DATABASE=prova
    networks:
      - mysql-compose-network
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - 8090:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - mysql-compose-network
networks: 
  mysql-compose-network:
    driver: bridge         